### ISSUE TITLE
Request for Environment Details

### ISSUE THREAD

**Issue by jiajqian** [navigator8972/consensus_normflow#1]
Hi,

Thank you for sharing your work on this project! I'm currently trying to set up the environment to run the code, but I've encountered some compatibility issues. To help me replicate your setup more accurately, could you please provide the specific versions of the key dependencies (e.g., PyTorch，garage) that you used?

Your guidance would be immensely helpful, and I really appreciate your time and effort.

Thanks again for your work!

Best regards,

**Comment by navigator8972** [comment]
Thanks for the interests. Please see the updated README.md. pybullet is probably 3.21 because pip list says 3.2.1.
